CREATE TABLE IF NOT EXISTS geo_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  website_url TEXT,
  optimization_target TEXT,
  supplemental_info TEXT,
  questions_generated_at TIMESTAMPTZ,
  questions_locked_at TIMESTAMPTZ,
  diagnosis_started_at TIMESTAMPTZ,
  initial_diagnosis_completed_at TIMESTAMPTZ,
  website_locked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT geo_projects_company_name_unique UNIQUE (company_name),
  CONSTRAINT geo_projects_company_name_not_blank CHECK (length(btrim(company_name)) > 0)
);

CREATE INDEX IF NOT EXISTS geo_projects_updated_at_idx ON geo_projects (updated_at DESC);
