ALTER TABLE geo_projects
  ADD COLUMN IF NOT EXISTS website_crawl_status TEXT NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS website_crawl_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS website_crawl_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS website_crawl_error TEXT,
  ADD COLUMN IF NOT EXISTS website_crawl_source TEXT,
  ADD COLUMN IF NOT EXISTS website_crawl_incomplete BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS website_pages_discovered INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS website_pages_succeeded INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS website_pages_failed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS questions_generation_status TEXT NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS questions_generation_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS questions_generation_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS questions_generation_error TEXT;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'geo_projects_website_crawl_status_check') THEN
    ALTER TABLE geo_projects ADD CONSTRAINT geo_projects_website_crawl_status_check
      CHECK (website_crawl_status IN ('not_started', 'crawling', 'completed', 'failed'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'geo_projects_questions_generation_status_check') THEN
    ALTER TABLE geo_projects ADD CONSTRAINT geo_projects_questions_generation_status_check
      CHECK (questions_generation_status IN ('not_started', 'generating', 'completed', 'failed'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'geo_projects_website_page_counts_check') THEN
    ALTER TABLE geo_projects ADD CONSTRAINT geo_projects_website_page_counts_check
      CHECK (website_pages_discovered >= 0 AND website_pages_succeeded >= 0 AND website_pages_failed >= 0);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS geo_project_website_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES geo_projects(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  body_text TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  error TEXT,
  discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fetched_at TIMESTAMPTZ,
  CONSTRAINT geo_project_website_pages_project_url_unique UNIQUE (project_id, url),
  CONSTRAINT geo_project_website_pages_status_check CHECK (status IN ('success', 'failed'))
);

CREATE INDEX IF NOT EXISTS geo_project_website_pages_project_idx ON geo_project_website_pages (project_id, id);

CREATE TABLE IF NOT EXISTS geo_project_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES geo_projects(id) ON DELETE CASCADE,
  position SMALLINT NOT NULL,
  question TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT geo_project_questions_position_check CHECK (position BETWEEN 1 AND 20),
  CONSTRAINT geo_project_questions_project_position_unique UNIQUE (project_id, position)
);

CREATE INDEX IF NOT EXISTS geo_project_questions_project_idx ON geo_project_questions (project_id, position);
