ALTER TABLE geo_projects
  ADD COLUMN IF NOT EXISTS initial_diagnosis_status TEXT NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS initial_recommendation_rate NUMERIC(5,4),
  ADD COLUMN IF NOT EXISTS initial_official_citation_rate NUMERIC(5,4),
  ADD COLUMN IF NOT EXISTS initial_diagnosis_at TIMESTAMPTZ;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'geo_projects_initial_diagnosis_status_check') THEN
    ALTER TABLE geo_projects ADD CONSTRAINT geo_projects_initial_diagnosis_status_check
      CHECK (initial_diagnosis_status IN ('not_started', 'running', 'analyzing', 'completed', 'failed'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'geo_projects_initial_diagnosis_rate_check') THEN
    ALTER TABLE geo_projects ADD CONSTRAINT geo_projects_initial_diagnosis_rate_check
      CHECK (
        (initial_recommendation_rate IS NULL OR (initial_recommendation_rate >= 0 AND initial_recommendation_rate <= 1))
        AND (initial_official_citation_rate IS NULL OR (initial_official_citation_rate >= 0 AND initial_official_citation_rate <= 1))
      );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS geo_diagnosis_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES geo_projects(id) ON DELETE CASCADE,
  run_type TEXT NOT NULL DEFAULT 'initial',
  status TEXT NOT NULL DEFAULT 'running',
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  summary_analysis JSONB,
  summary_model TEXT,
  summary_error TEXT,
  recommendation_rate NUMERIC(5,4),
  official_citation_rate NUMERIC(5,4),
  CONSTRAINT geo_diagnosis_runs_project_type_unique UNIQUE (project_id, run_type),
  CONSTRAINT geo_diagnosis_runs_type_check CHECK (run_type = 'initial'),
  CONSTRAINT geo_diagnosis_runs_status_check CHECK (status IN ('running', 'analyzing', 'completed', 'failed')),
  CONSTRAINT geo_diagnosis_runs_rate_check CHECK (
    (recommendation_rate IS NULL OR (recommendation_rate >= 0 AND recommendation_rate <= 1))
    AND (official_citation_rate IS NULL OR (official_citation_rate >= 0 AND official_citation_rate <= 1))
  )
);

CREATE INDEX IF NOT EXISTS geo_diagnosis_runs_project_idx ON geo_diagnosis_runs (project_id, id DESC);

CREATE TABLE IF NOT EXISTS geo_diagnosis_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES geo_diagnosis_runs(id) ON DELETE CASCADE,
  position SMALLINT NOT NULL,
  question TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  answer_text TEXT,
  citation_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  response_model TEXT,
  recommended BOOLEAN,
  official_citation BOOLEAN,
  error TEXT,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT geo_diagnosis_answers_run_position_unique UNIQUE (run_id, position),
  CONSTRAINT geo_diagnosis_answers_position_check CHECK (position BETWEEN 1 AND 20),
  CONSTRAINT geo_diagnosis_answers_status_check CHECK (status IN ('pending', 'running', 'success', 'failed')),
  CONSTRAINT geo_diagnosis_answers_citations_array_check CHECK (jsonb_typeof(citation_urls) = 'array')
);

CREATE INDEX IF NOT EXISTS geo_diagnosis_answers_run_idx ON geo_diagnosis_answers (run_id, position);
