CREATE TABLE IF NOT EXISTS geo_article_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES geo_projects(id) ON DELETE CASCADE,
  requested_model TEXT NOT NULL,
  response_model TEXT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS geo_article_batches_project_idx
  ON geo_article_batches (project_id, id DESC);

CREATE TABLE IF NOT EXISTS geo_project_articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES geo_projects(id) ON DELETE CASCADE,
  batch_id BIGINT NOT NULL REFERENCES geo_article_batches(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  question_position SMALLINT NOT NULL,
  content_html TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  publish_status TEXT NOT NULL DEFAULT 'pending',
  confirmed_at TIMESTAMPTZ,
  CONSTRAINT geo_project_articles_question_position_check CHECK (question_position BETWEEN 1 AND 20),
  CONSTRAINT geo_project_articles_title_not_blank CHECK (length(btrim(title)) > 0),
  CONSTRAINT geo_project_articles_content_not_blank CHECK (length(btrim(content_html)) > 0),
  CONSTRAINT geo_project_articles_publish_status_check CHECK (publish_status IN ('pending', 'published'))
);

CREATE INDEX IF NOT EXISTS geo_project_articles_project_idx
  ON geo_project_articles (project_id, id DESC);

CREATE INDEX IF NOT EXISTS geo_project_articles_batch_idx
  ON geo_project_articles (batch_id, id);

CREATE UNIQUE INDEX IF NOT EXISTS geo_project_articles_project_title_unique
  ON geo_project_articles (project_id, lower(title));
